export const PLAYERS_DATA = [
    {
        "id": 1,
        "firstName": "JOS",
        "lastName": "BUTTLER",
        "role": "Wicketkeeper Batter",
        "country": "ENG",
        "age": 34,
        "previousTeam": "RR",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Jos_Buttler_in_2023.jpg/500px-Jos_Buttler_in_2023.jpg",
        "iplStat": "3582 Runs",
        "set": "M1"
    },
    {
        "id": 2,
        "firstName": "SHREYAS",
        "lastName": "IYER",
        "role": "Batsman",
        "country": "IND",
        "age": 30,
        "previousTeam": "KKR",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Shreyas_Iyer_snapped_at_the_airport_%28Cropped%29.jpg",
        "iplStat": "3127 Runs",
        "set": "M1"
    },
    {
        "id": 3,
        "firstName": "RISHABH",
        "lastName": "PANT",
        "role": "Wicketkeeper Batter",
        "country": "IND",
        "age": 27,
        "previousTeam": "DC",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Rishabh_Pant.jpg/500px-Rishabh_Pant.jpg",
        "iplStat": "3284 Runs",
        "set": "M1"
    },
    {
        "id": 4,
        "firstName": "KAGISO",
        "lastName": "RABADA",
        "role": "Bowler",
        "country": "SA",
        "age": 29,
        "previousTeam": "PBKS",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Rabada.jpg/500px-Rabada.jpg",
        "iplStat": "117 Wickets",
        "set": "M1"
    },
    {
        "id": 5,
        "firstName": "ARSHDEEP",
        "lastName": "SINGH",
        "role": "Bowler",
        "country": "IND",
        "age": 25,
        "previousTeam": "PBKS",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Arshdeep_Singh_Family_%28Cropped%29.jpg/500px-Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Arshdeep_Singh_Family_%28Cropped%29.jpg",
        "iplStat": "76 Wickets",
        "set": "M1"
    },
    {
        "id": 6,
        "firstName": "MITCHELL",
        "lastName": "STARC",
        "role": "Bowler",
        "country": "AUS",
        "age": 34,
        "previousTeam": "KKR",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/3/38/Mitchell_Starc_2023.jpg",
        "iplStat": "51 Wickets",
        "set": "M1"
    },
    {
        "id": 7,
        "firstName": "PHIL",
        "lastName": "SALT",
        "role": "Wicketkeeper Batter",
        "country": "ENG",
        "age": 28,
        "previousTeam": "KKR",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/2_02_Phil_Salt.jpg/500px-2_02_Phil_Salt.jpg",
        "iplStat": "653 Runs",
        "set": "M2"
    },
    {
        "id": 8,
        "firstName": "DEVON",
        "lastName": "CONWAY",
        "role": "Wicketkeeper Batter",
        "country": "NZ",
        "age": 33,
        "previousTeam": "CSK",
        "basePrice": "2.00",
        "imageUrl": "https://ui-avatars.com/api/?name=DEVON%20CONWAY&background=026a64&color=fff&size=500",
        "iplStat": "924 Runs",
        "set": "M2"
    },
    {
        "id": 9,
        "firstName": "LIAM",
        "lastName": "LIVINGSTONE",
        "role": "All-Rounder",
        "country": "ENG",
        "age": 31,
        "previousTeam": "PBKS",
        "basePrice": "2.00",
        "imageUrl": "https://ui-avatars.com/api/?name=LIAM%20LIVINGSTONE&background=026a64&color=fff&size=500",
        "iplStat": "939 Runs",
        "set": "M2"
    },
    {
        "id": 10,
        "firstName": "GLENN",
        "lastName": "MAXWELL",
        "role": "All-Rounder",
        "country": "AUS",
        "age": 36,
        "previousTeam": "RCB",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Glen_Maxwell_2026_%28cropped%29.jpg/500px-Glen_Maxwell_2026_%28cropped%29.jpg",
        "iplStat": "2771 Runs",
        "set": "M2"
    },
    {
        "id": 11,
        "firstName": "MARCUS",
        "lastName": "STOINIS",
        "role": "All-Rounder",
        "country": "AUS",
        "age": 35,
        "previousTeam": "LSG",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/2018.01.21.15.22.25-Stoinis_%2839081521620%29.jpg/500px-2018.01.21.15.22.25-Stoinis_%2839081521620%29.jpg",
        "iplStat": "1477 Runs",
        "set": "M2"
    },
    {
        "id": 12,
        "firstName": "DAVID",
        "lastName": "MILLER",
        "role": "Batsman",
        "country": "SA",
        "age": 35,
        "previousTeam": "GT",
        "basePrice": "1.50",
        "imageUrl": "https://ui-avatars.com/api/?name=DAVID%20MILLER&background=026a64&color=fff&size=500",
        "iplStat": "2714 Runs",
        "set": "M2"
    },
    {
        "id": 13,
        "firstName": "JOSH",
        "lastName": "HAZLEWOOD",
        "role": "Bowler",
        "country": "AUS",
        "age": 33,
        "previousTeam": "RCB",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/2018_Josh_Hazlewood_%28cropped%29.jpg/500px-2018_Josh_Hazlewood_%28cropped%29.jpg",
        "iplStat": "35 Wickets",
        "set": "FA1"
    },
    {
        "id": 14,
        "firstName": "ADIL",
        "lastName": "RASHID",
        "role": "Bowler",
        "country": "ENG",
        "age": 36,
        "previousTeam": "SRH",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/1_13_Adil_Rashid_%28cropped%29.jpg/500px-1_13_Adil_Rashid_%28cropped%29.jpg",
        "iplStat": "26 Wickets",
        "set": "FA1"
    },
    {
        "id": 15,
        "firstName": "WANINDU",
        "lastName": "HASARANGA",
        "role": "All-Rounder",
        "country": "SL",
        "age": 27,
        "previousTeam": "RCB",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Waniya.jpg/500px-Waniya.jpg",
        "iplStat": "35 Wickets",
        "set": "AL1"
    },
    {
        "id": 16,
        "firstName": "SHARDUL",
        "lastName": "THAKUR",
        "role": "All-Rounder",
        "country": "IND",
        "age": 32,
        "previousTeam": "CSK",
        "basePrice": "2.00",
        "imageUrl": "https://ui-avatars.com/api/?name=SHARDUL%20THAKUR&background=026a64&color=fff&size=500",
        "iplStat": "94 Wickets",
        "set": "AL1"
    },
    {
        "id": 17,
        "firstName": "UMESH",
        "lastName": "YADAV",
        "role": "Bowler",
        "country": "IND",
        "age": 37,
        "previousTeam": "GT",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Umesh_Yadav.jpg",
        "iplStat": "136 Wickets",
        "set": "FA1"
    },
    {
        "id": 18,
        "firstName": "AJINKYA",
        "lastName": "RAHANE",
        "role": "Batsman",
        "country": "IND",
        "age": 36,
        "previousTeam": "CSK",
        "basePrice": "1.50",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/9/96/Ajinkya_Rahane_2016_%28cropped%29.jpg",
        "iplStat": "4642 Runs",
        "set": "BA1"
    },
    {
        "id": 19,
        "firstName": "MANISH",
        "lastName": "PANDEY",
        "role": "Batsman",
        "country": "IND",
        "age": 35,
        "previousTeam": "DC",
        "basePrice": "0.50",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Manish_Pandey_%283%29.jpg/500px-Manish_Pandey_%283%29.jpg",
        "iplStat": "3808 Runs",
        "set": "BA1"
    },
    {
        "id": 20,
        "firstName": "KARUN",
        "lastName": "NAIR",
        "role": "Batsman",
        "country": "IND",
        "age": 33,
        "previousTeam": "RR",
        "basePrice": "0.50",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/d/d8/Karun_nair_With_Rashid_Zirak.jpg",
        "iplStat": "1496 Runs",
        "set": "BA1"
    },
    {
        "id": 21,
        "firstName": "STEVE",
        "lastName": "SMITH",
        "role": "Batsman",
        "country": "AUS",
        "age": 35,
        "previousTeam": "RR",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/STEVE_SMITH_%2811705303043%29.jpg/500px-STEVE_SMITH_%2811705303043%29.jpg",
        "iplStat": "2485 Runs",
        "set": "BA1"
    },
    {
        "id": 22,
        "firstName": "DAVID",
        "lastName": "WARNER",
        "role": "Batsman",
        "country": "AUS",
        "age": 37,
        "previousTeam": "DC",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/1/1d/David_Warner_%28Actor%29_Rory_Lewis_Photographer.jpg",
        "iplStat": "6565 Runs",
        "set": "BA1"
    },
    {
        "id": 23,
        "firstName": "JONNY",
        "lastName": "BAIRSTOW",
        "role": "Wicketkeeper Batter",
        "country": "ENG",
        "age": 34,
        "previousTeam": "PBKS",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/2_05_Bairstow_out.jpg/500px-2_05_Bairstow_out.jpg",
        "iplStat": "1589 Runs",
        "set": "BA1"
    },
    {
        "id": 24,
        "firstName": "QUINTON",
        "lastName": "DE KOCK",
        "role": "Wicketkeeper Batter",
        "country": "SA",
        "age": 31,
        "previousTeam": "LSG",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/QUINTON_DE_KOCK_%2815681398316%29.jpg/500px-QUINTON_DE_KOCK_%2815681398316%29.jpg",
        "iplStat": "3157 Runs",
        "set": "BA1"
    },
    {
        "id": 25,
        "firstName": "TRAVIS",
        "lastName": "HEAD",
        "role": "Batsman",
        "country": "AUS",
        "age": 30,
        "previousTeam": "SRH",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Travis_Head_bowling_at_Perth_Stadium%2C_First_Test_Australia_versus_West_Indies%2C_2_December_2022_03_%28cropped%29.jpg/500px-Travis_Head_bowling_at_Perth_Stadium%2C_First_Test_Australia_versus_West_Indies%2C_2_December_2022_03_%28cropped%29.jpg",
        "iplStat": "772 Runs",
        "set": "BA1"
    },
    {
        "id": 26,
        "firstName": "KANE",
        "lastName": "WILLIAMSON",
        "role": "Batsman",
        "country": "NZ",
        "age": 34,
        "previousTeam": "GT",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/2/2a/Kane_Williamson_in_2019.jpg",
        "iplStat": "2128 Runs",
        "set": "BA1"
    },
    {
        "id": 27,
        "firstName": "MAYANK",
        "lastName": "AGARWAL",
        "role": "Batsman",
        "country": "IND",
        "age": 33,
        "previousTeam": "SRH",
        "basePrice": "1.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/2_38_Agarwal_mugshot.jpg/500px-2_38_Agarwal_mugshot.jpg",
        "iplStat": "2597 Runs",
        "set": "BA1"
    },
    {
        "id": 28,
        "firstName": "PRITHVI",
        "lastName": "SHAW",
        "role": "Batsman",
        "country": "IND",
        "age": 25,
        "previousTeam": "DC",
        "basePrice": "1.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a8/Prithvi_shaw.png",
        "iplStat": "1892 Runs",
        "set": "BA1"
    },
    {
        "id": 29,
        "firstName": "RAHUL",
        "lastName": "TRIPATHI",
        "role": "Batsman",
        "country": "IND",
        "age": 33,
        "previousTeam": "SRH",
        "basePrice": "0.75",
        "imageUrl": "https://ui-avatars.com/api/?name=RAHUL%20TRIPATHI&background=026a64&color=fff&size=500",
        "iplStat": "2236 Runs",
        "set": "BA1"
    },
    {
        "id": 30,
        "firstName": "DEEPAK",
        "lastName": "HOODA",
        "role": "All-Rounder",
        "country": "IND",
        "age": 29,
        "previousTeam": "LSG",
        "basePrice": "0.75",
        "imageUrl": "https://ui-avatars.com/api/?name=DEEPAK%20HOODA&background=026a64&color=fff&size=500",
        "iplStat": "1300 Runs",
        "set": "AL1"
    },
    {
        "id": 31,
        "firstName": "WASHINGTON",
        "lastName": "SUNDAR",
        "role": "All-Rounder",
        "country": "IND",
        "age": 25,
        "previousTeam": "SRH",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Washington_Sundar.jpg/500px-Washington_Sundar.jpg",
        "iplStat": "36 Wickets",
        "set": "AL1"
    },
    {
        "id": 32,
        "firstName": "AXAR",
        "lastName": "PATEL",
        "role": "All-Rounder",
        "country": "IND",
        "age": 30,
        "previousTeam": "DC",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Axar_Patel_in_PMO_New_Delhi.jpg",
        "iplStat": "112 Wickets",
        "set": "AL1"
    },
    {
        "id": 33,
        "firstName": "RAVICHANDRAN",
        "lastName": "ASHWIN",
        "role": "All-Rounder",
        "country": "IND",
        "age": 37,
        "previousTeam": "RR",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/The_Minister_of_State_for_Youth_Affairs_and_Sports_%28Independent_Charge%29%2C_Shri_Sarbananda_Sonowal_conferring_the_Arjuna_Award_on_cricketer_Ravichandran_Ashwin%2C_in_New_Delhi_on_July_31%2C_2015_cropped.jpg/500px-thumbnail.jpg",
        "iplStat": "174 Wickets",
        "set": "AL1"
    },
    {
        "id": 34,
        "firstName": "YUZVENDRA",
        "lastName": "CHAHAL",
        "role": "Bowler",
        "country": "IND",
        "age": 34,
        "previousTeam": "RR",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Yuzvendra_Chahal_in_PMO_New_Delhi.jpg/500px-Yuzvendra_Chahal_in_PMO_New_Delhi.jpg",
        "iplStat": "200 Wickets",
        "set": "FA1"
    },
    {
        "id": 35,
        "firstName": "KULDEEP",
        "lastName": "YADAV",
        "role": "Bowler",
        "country": "IND",
        "age": 30,
        "previousTeam": "DC",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Kuldeep_Yadav_in_PMO_New_Delhi.jpg/500px-Kuldeep_Yadav_in_PMO_New_Delhi.jpg",
        "iplStat": "87 Wickets",
        "set": "FA1"
    },
    {
        "id": 36,
        "firstName": "JASPRIT",
        "lastName": "BUMRAH",
        "role": "Bowler",
        "country": "IND",
        "age": 31,
        "previousTeam": "MI",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Jasprit_Bumrah_in_PMO_New_Delhi.jpg/500px-Jasprit_Bumrah_in_PMO_New_Delhi.jpg",
        "iplStat": "165 Wickets",
        "set": "FA1"
    },
    {
        "id": 37,
        "firstName": "MOHAMMED",
        "lastName": "SHAMI",
        "role": "Bowler",
        "country": "IND",
        "age": 34,
        "previousTeam": "GT",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Mohammed_Shami_Arjuna_Award_%28cropped%29.jpg/500px-Mohammed_Shami_Arjuna_Award_%28cropped%29.jpg",
        "iplStat": "127 Wickets",
        "set": "FA1"
    },
    {
        "id": 38,
        "firstName": "MOHAMMED",
        "lastName": "SIRAJ",
        "role": "Bowler",
        "country": "IND",
        "age": 30,
        "previousTeam": "RCB",
        "basePrice": "2.00",
        "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/d/da/Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Mohammad_Siraj_%28cropped%29.jpg",
        "iplStat": "83 Wickets",
        "set": "FA1"
    },
    {
        "id": 39,
        "firstName": "TRENT",
        "lastName": "BOULT",
        "role": "Bowler",
        "country": "NZ",
        "age": 34,
        "previousTeam": "RR",
        "basePrice": "2.00",
        "imageUrl": "https://ui-avatars.com/api/?name=TRENT%20BOULT&background=026a64&color=fff&size=500",
        "iplStat": "113 Wickets",
        "set": "FA1"
    },
    {
        "id": 40,
        "firstName": "PAT",
        "lastName": "CUMMINS",
        "role": "All-Rounder",
        "country": "AUS",
        "age": 31,
        "previousTeam": "SRH",
        "basePrice": "2.00",
        "imageUrl": "https://ui-avatars.com/api/?name=PAT%20CUMMINS&background=026a64&color=fff&size=500",
        "iplStat": "63 Wickets",
        "set": "AL1"
    },
    {
        "id": 41,
        "firstName": "SAM",
        "lastName": "CURRAN",
        "role": "All-Rounder",
        "country": "ENG",
        "age": 26,
        "previousTeam": "PBKS",
        "basePrice": "2.00",
        "imageUrl": "https://ui-avatars.com/api/?name=SAM%20CURRAN&background=026a64&color=fff&size=500",
        "iplStat": "46 Wickets",
        "set": "AL1"
    },
    {
        "id": 42,
        "firstName": "BEN",
        "lastName": "STOKES",
        "role": "All-Rounder",
        "country": "ENG",
        "age": 33,
        "previousTeam": "CSK",
        "basePrice": "2.00",
        "imageUrl": "https://ui-avatars.com/api/?name=BEN%20STOKES&background=026a64&color=fff&size=500",
        "iplStat": "935 Runs",
        "set": "AL1"
    },
    {
        "id": 43,
        "firstName": "MOEEN",
        "lastName": "ALI",
        "role": "All-Rounder",
        "country": "ENG",
        "age": 37,
        "previousTeam": "CSK",
        "basePrice": "2.00",
        "imageUrl": "https://ui-avatars.com/api/?name=MOEEN%20ALI&background=026a64&color=fff&size=500",
        "iplStat": "1162 Runs",
        "set": "AL1"
    },
    {
        "id": 44,
        "firstName": "RASHID",
        "lastName": "KHAN",
        "role": "Bowler",
        "country": "AFG",
        "age": 26,
        "previousTeam": "GT",
        "basePrice": "2.00",
        "imageUrl": "https://ui-avatars.com/api/?name=RASHID%20KHAN&background=026a64&color=fff&size=500",
        "iplStat": "149 Wickets",
        "set": "FA1"
    },
    {
        "id": 45,
        "firstName": "RAHMANULLAH",
        "lastName": "GURBAZ",
        "role": "Wicketkeeper Batter",
        "country": "AFG",
        "age": 23,
        "previousTeam": "KKR",
        "basePrice": "0.50",
        "imageUrl": "https://ui-avatars.com/api/?name=RAHMANULLAH%20GURBAZ&background=026a64&color=fff&size=500",
        "iplStat": "289 Runs",
        "set": "BA1"
    },
    {
        "id": 46,
        "firstName": "NICHOLAS",
        "lastName": "POORAN",
        "role": "Wicketkeeper Batter",
        "country": "WI",
        "age": 29,
        "previousTeam": "LSG",
        "basePrice": "2.00",
        "imageUrl": "https://ui-avatars.com/api/?name=NICHOLAS%20POORAN&background=026a64&color=fff&size=500",
        "iplStat": "1769 Runs",
        "set": "BA1"
    },
    {
        "id": 47,
        "firstName": "SHIMRON",
        "lastName": "HETMYER",
        "role": "Batsman",
        "country": "WI",
        "age": 28,
        "previousTeam": "RR",
        "basePrice": "1.50",
        "imageUrl": "https://ui-avatars.com/api/?name=SHIMRON%20HETMYER&background=026a64&color=fff&size=500",
        "iplStat": "1135 Runs",
        "set": "BA1"
    },
    {
        "id": 48,
        "firstName": "ANDRE",
        "lastName": "RUSSELL",
        "role": "All-Rounder",
        "country": "WI",
        "age": 36,
        "previousTeam": "KKR",
        "basePrice": "2.00",
        "imageUrl": "https://ui-avatars.com/api/?name=ANDRE%20RUSSELL&background=026a64&color=fff&size=500",
        "iplStat": "2413 Runs",
        "set": "AL1"
    },
    {
        "id": 49,
        "firstName": "SUNIL",
        "lastName": "NARINE",
        "role": "All-Rounder",
        "country": "WI",
        "age": 36,
        "previousTeam": "KKR",
        "basePrice": "2.00",
        "imageUrl": "https://ui-avatars.com/api/?name=SUNIL%20NARINE&background=026a64&color=fff&size=500",
        "iplStat": "165 Wickets",
        "set": "AL1"
    },
    {
        "id": 50,
        "firstName": "DWAYNE",
        "lastName": "BRAVO",
        "role": "All-Rounder",
        "country": "WI",
        "age": 40,
        "previousTeam": "CSK",
        "basePrice": "1.50",
        "imageUrl": "https://ui-avatars.com/api/?name=DWAYNE%20BRAVO&background=026a64&color=fff&size=500",
        "iplStat": "183 Wickets",
        "set": "AL1"
    }
];