export const PLAYERS_DATA = [
    {
        "id": 1,
        "firstName": "JOS",
        "lastName": "BUTTLER",
        "role": "Wicketkeeper Batter",
        "country": "ENG",
        "age": 34,
        "previousTeam": "RR",
        "basePrice": "2.00",
        "imageUrl": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/509.png",
        "iplStat": "3582 Runs",
        "set": "M1"
    },
    {
        "id": 2,
        "firstName": "SHREYAS",
        "lastName": "IYER",
        "role": "Batsman",
        "country": "IND",
        "age": 30,
        "previousTeam": "KKR",
        "basePrice": "2.00",
        "imageUrl": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/1563.png",
        "iplStat": "3127 Runs",
        "set": "M1"
    },
    {
        "id": 3,
        "firstName": "RISHABH",
        "lastName": "PANT",
        "role": "Wicketkeeper Batter",
        "country": "IND",
        "age": 27,
        "previousTeam": "DC",
        "basePrice": "2.00",
        "imageUrl": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/2972.png",
        "iplStat": "3284 Runs",
        "set": "M1"
    },
    {
        "id": 4,
        "firstName": "KAGISO",
        "lastName": "RABADA",
        "role": "Bowler",
        "country": "SA",
        "age": 29,
        "previousTeam": "PBKS",
        "basePrice": "2.00",
        "imageUrl": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/116.png",
        "iplStat": "117 Wickets",
        "set": "M1"
    },
    {
        "id": 5,
        "firstName": "ARSHDEEP",
        "lastName": "SINGH",
        "role": "Bowler",
        "country": "IND",
        "age": 26,
        "previousTeam": "PBKS",
        "basePrice": "2.00",
        "imageUrl": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/4698.png",
        "iplStat": "76 Wickets",
        "set": "M1"
    },
    {
        "id": 6,
        "firstName": "MITCHELL",
        "lastName": "STARC",
        "role": "Bowler",
        "country": "AUS",
        "age": 35,
        "previousTeam": "KKR",
        "basePrice": "2.00",
        "imageUrl": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/114.png",
        "iplStat": "51 Wickets",
        "set": "M1"
    },
    {
        "id": 7,
        "firstName": "YUZVENDRA",
        "lastName": "CHAHAL",
        "role": "Bowler",
        "country": "IND",
        "age": 34,
        "previousTeam": "RR",
        "basePrice": "2.00",
        "imageUrl": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/111.png",
        "iplStat": "200 Wickets",
        "set": "M2"
    },
    {
        "id": 8,
        "firstName": "LIAM",
        "lastName": "LIVINGSTONE",
        "role": "All-Rounder",
        "country": "ENG",
        "age": 31,
        "previousTeam": "PBKS",
        "basePrice": "2.00",
        "imageUrl": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/3644.png",
        "iplStat": "939 Runs",
        "set": "M2"
    },
    {
        "id": 9,
        "firstName": "DAVID",
        "lastName": "MILLER",
        "role": "Batsman",
        "country": "SA",
        "age": 35,
        "previousTeam": "GT",
        "basePrice": "1.50",
        "imageUrl": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/187.png",
        "iplStat": "2714 Runs",
        "set": "M2"
    },
    {
        "id": 10,
        "firstName": "KL",
        "lastName": "RAHUL",
        "role": "Wicketkeeper Batter",
        "country": "IND",
        "age": 32,
        "previousTeam": "LSG",
        "basePrice": "2.00",
        "imageUrl": "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2024/1125.png",
        "iplStat": "4163 Runs",
        "set": "M2"
    }
];
